### ISSUE TITLE
Fix: recruit page 관련 리뷰 반영 및 수정 사항

### ISSUE THREAD

**Issue by limgahyun** [kahluaband/Homepage_client_ver2.0#14]
## 🍒 IssueName
> 리뷰 사항 수정

## 📝 Description
> recruit  page에서 발생하는 오류 해결

## 🌱 Todo
- [x] card 컴포넌트화
- [x] nav bar 색상 변경 (+블러처리)
- [x] apply페이지 이후로 footer 숨김처리 -> 지은이꺼 머지한 후에 수정 + h-auto로 수정
- [x] recruit페이지 초기 접속시 FAQ css 깨지는 문제 해결
- [x] Link 버튼 비활성화 기능 추가
- [ ] apply form - input 한글자마다 rerendering되는 문제 해결
- [x] `recruit/notice` `recruit/apply` `recruit/complete` 페이지에서 header위로 여백 생기는 문제 해결
- [x] `recruit/complete` 과 같은 페이지에서 스크린 너비가 360px 또는 애매할 때, 글씨 줄바꿈때문에 안예뻐보이는 문제 해결
- [ ] `/recruit` `requirement`에서 `setInnerHTML` 사용하지 않는 방법으로 리팩토링 + 일부 컨텐츠 text-gray-10 변경
- [ ] `/recruit/apply/complete` url  접근 막아두기
    https://nextjs.org/docs/pages/api-reference/next-config-js/redirects#wildcard-path-matching
- [ ] `MultipleOptionbox.tsx` 리팩토링
- [x] recruit 정보 information으로 분리하기
