### ISSUE TITLE
Feat: 제작자 페이지 반응형

### ISSUE THREAD

**Issue by letthem** [kahluaband/Homepage_client_ver2.0#26]
## 🍒 IssueName
> 제작자 페이지 반응형

## 📝 Description
> 제작자 페이지 반응형

## 🌱 Todo
- [x] 배경 반응형
- [x] Title 반응형
- [x] ContributorCard 이미지 반응형
- [x] ContributorCard 내부 요소 반응형
- [x] ContributorCard dt/pad & ph 나눠 반응형
- [x] 디자이너분 이메일 수정사항 반영
