### ISSUE TITLE
Feat: 어드민 페이지 통신 관련 

### ISSUE THREAD

**Issue by caminobelllo** [kahluaband/Homepage_client_ver2.0#28]
## 🍒 IssueName
> 어드민 페이지에 관련한 모든 통신 로직 및 기능 구현 

## 📝 Description
> 어드민 로그인, 페이지 접근 제한 및 데이터 불러오기 등의 모든 통신 관련 기능을 구현합니다.

## 🌱 Todo
- [x] 어드민 로그인 구현
- [x] 어드민 페이지 접근 권한 제어
- [x] 어드민 로그아웃 구현
- [x] 지원 필터링 기능 구현
- [x] 예매 필터링 기능 구현
- [x] 예매자 리스트 불러오기
- [x] 지원자 리스트 불러오기
- [x] 예매 상세 데이터 불러오기
- [x] 지원 상세 데이터 불러오기
