### ISSUE TITLE
Fix: 티켓 페이지 배포 후 이슈

### ISSUE THREAD

**Issue by yumzen** [kahluaband/Homepage_client_ver2.0#50]
## 🍒 IssueName
> 이슈 명을 작성해주세요.

## 📝 Description
> 이슈에 대해 간결하게 설명해주세요.

## 🌱 Todo
- [x] 공연 title width 적용하기
- [x] 이미지 & 컴포넌트 겹치는 문제 해결하기
- [x] 공연 정보 선택 컴포넌트와 Header 겹침 문제
- [x] 제출확인 모달창 제출 버튼이 깨짐
- [x] 인원 추가 적용 문제 -> 통신까지
